#=
# Matlab file generation functions
=#

function matlab_main_file()
    file = genfiles.main;
    println(file, "clear;");
    # for using HOMG
    println(file, "import homg.*;");
    println(file, "");
    # These are always included
    println(file, "addpath('operators');");
    println(file, "");
    println(file, "Config;");
    println(file, "Mesh;");
    println(file, "Genfunction;");
    println(file, "Problem;");
    println(file, "Bilinear;");
    println(file, "Linear;");
    println(file, "");
    
    # This should be generated by solve()
    # Just for testing:
    println(file, "u = LHS\\RHS;");
    println(file, "");
    
    # Output should be generated by finalize?
    # Just for testing:
    println(file, "N1d = nelem*config.basis_order_min+1;");
    println(file, "surf(reshape(u,N1d,N1d));");
    println(file, "");
end

function matlab_config_file()
    file = genfiles.config;
    # Duplicate the config struct
    for f in fieldnames(Femshop_config)
        println(file, "config."*string(f)*" = "*matlab_gen_string(getfield(config, f))*";");
    end
end

function matlab_prob_file()
    file = genfiles.problem;
    # Duplicate the prob struct
    for f in fieldnames(Femshop_prob)
        println(file, "prob."*string(f)*" = "*matlab_gen_string(getfield(prob, f))*";");
    end
end

function matlab_mesh_file()
    file = genfiles.mesh;
    # For using HOMG
    if config.dimension == 1
        nelem = mesh_data.nel;
    elseif config.dimension == 2
        nelem = Int(round(sqrt(mesh_data.nel)));
    elseif config.dimension == 3
        nelem = Int(round(cbrt(mesh_data.nel)));
    end
    println(file, "nelem = "*string(nelem)*";");
    println(file, "mesh = homg.hexmesh(repmat(nelem, 1, config.dimension), @homg.xform.identity);");
    println(file, "bdry = mesh.get_boundary_node_indices(config.basis_order_min);");
end

function isfunction(g)
    for b in bilinears
        if b.name == g.name
            return false;
        end
    end
    for l in linears
        if l.name == g.name
            return false;
        end
    end
    return true;
end
function matlab_genfunction_file()
    file = genfiles.genfunction;
    for i = 1:length(genfunctions)
        if isfunction(genfunctions[i])
            println(file, genfunctions[i].name*"_fun = @(x,y,z,t) ("*genfunctions[i].str*");");
            # Evaluate them at grid points and make them vectors. Make sense???
            println(file, genfunctions[i].name*" = mesh.evaluate("*genfunctions[i].name*"_fun, config.basis_order_min, 'gll');");
        end
    end
    
    # assign variable and coefficient symbols to these vectors
    for v in variables
        println(file, string(v.symbol)*" = '"*string(v.symbol)*"';");
    end
    for v in coefficients
        if typeof(v.value[1]) == GenFunction
            println(file, string(v.symbol)*" = "*v.value[1].name*";");
        else
            println(file, string(v.symbol)*" = "*string(v.value[1])*";");
        end
    end
end

function matlab_bilinear_file(bl)
    file = genfiles.bilinear;
    println(file, "args.left = true;");
    println(file, "args.mesh = mesh;");
    println(file, "args.config = config;");
    println(file, "LHS = "*bl.str*";");
    println(file, "LHS(bdry,:) = 0;");
    println(file, "LHS((size(LHS,1)+1)*(bdry-1)+1) = 1;"); # dirichlet bc
end

function matlab_linear_file(l)
    file = genfiles.linear;
    println(file, "args.left = false;");
    println(file, "args.mesh = mesh;");
    println(file, "args.config = config;");
    println(file, "RHS = "*l.str*";");
    println(file, "RHS(bdry) = prob.bc_func(bdry);"); # dirichlet bc
end

function matlab_stepper_file()
    file = genfiles.stepper;
end
