%This file was generated by Femshop.

%{
Mesh
%}
nelem = 30;
mesh = homg.hexmesh(repmat(nelem, 1, config.dimension), @homg.xform.identity);
bdry = mesh.get_boundary_node_indices(config.basis_order_min);
