%This file was generated by Femshop.

%{
Linear term
%}
mesh.set_order(order);
refel = homg.refel ( mesh.dim, order );
dof = prod(mesh.nelems*order + 1);
ne  = prod(mesh.nelems);
NP = (order+1)^mesh.dim;
NPNP = NP * NP;
RHS = zeros(dof,1);

% loop over elements
for e=1:ne
    pts = mesh.element_nodes(e, refel);
    [detJac, Jac]  = mesh.geometric_factors(refel, pts);
    idx = mesh.get_node_indices (e, order);
gpts = mesh.element_gauss(e, refel);
coef_0_1 = genfunction_1(idx);

elVec = refel.Q' * diag(refel.W .* detJ) * (refel.Q * coef_0_1);


    RHS(idx) = elVec;
end

RHS(bdry) = prob.bc_func(bdry);
