%This file was generated by Femshop.

%{
Bilinear term
%}
args.left = true;
args.mesh = mesh;
args.config = config;
LHS = -(stiffness_operator(u, args));
LHS(bdry,:) = 0;
LHS((size(LHS,1)+1)*(bdry-1)+1) = 1;
