%This file was generated by Femshop.

%{
Problem info
%}
prob.bc_type = ['Dirichlet' '' '' ];
prob.bid = [1 0 0 ];
prob.bc_func = [genfunction_0   ];
prob.time_dependent = false;
prob.end_time = 0.0;
prob.initial = [];
prob.lhs_time_deriv = [];
